### PR TITLE
Adding Hover to the social media icons Issue#124

### LINKED ISSUE #124: Transition Effect On Hover
## Problem statement
- add transition effects to social media icons on hover, located at the footer of home page and members page

image

## Possible solution
- transform scale(1.2), transition timing 0.5s

### PR DESCRIPTION
**Pull request by Marian1200**

### CODE REVIEW

**Review by babboe1 — CHANGES_REQUESTED** [review]
Hello Marian1200,
There are some few changes you need to make;
- The transition effect should be added on the icon's normal state not on the hover state
- the hover effect should also be done to the social media icons in the other pages as stated in the issue

**Comment by Marian1200** [comment]
Sorry my bad i must have misunderstood, Iet me fix it for you,

**Comment by Marian1200** [comment]
Hello @babboe1, I have made the necessary changes and removed the faulty code from before, this is my first time helping on an open source so let me know if i need to do anything extra! 

Thank you !

**Review by babboe1 — CHANGES_REQUESTED** [review]
Hello Marian1200,
I appreciate the efforts you have shown in contributing to your first open source 

But it seems i wasn't clear with my explanation, and i apologize for that
What you added was an animation that runs infinitely without the hover state, animation is not needed

The former PR you made was very close ,
all you had to change was remove the transition line of code from the

 .fa-twitter:hover, .fa-instragram:hover, .fa-linkedin:hover {} state 
 
and add it to the

 .fa-twitter, .fa-instagram, .fa-linkedin {} , 

And then effect the change in the other page

Perhaps, If my explain isn't clear enough, we could get on a google meet, so i could show you what i mean

**Comment by Marian1200** [comment]
Hey  @babboe1  I am so sorry I hope I didn't cause you any trouble, I have made new changes and I hope that's what you are looking for, please do let me know if there is anything I can do to help you out.

Thank you for understanding and explaining I appreciate it

**Review by babboe1 — APPROVED** [review]
Hello Marian1200.,
Thank you for contributing

I am glad you were able to get a take away from this task
Your PR looks good to me

**Pull request merged**
