### PR TITLE
Added Temitope's Profile

### PR DESCRIPTION
**Pull request by TemitopeAgbaje**

### CODE REVIEW

**Comment by babboe1** [comment]
Hello Temitope,
Thank you for contributing to this project
You have taken the first step and you are halfway done already,

I just reviewed your PR, and I noticed you have some merge conflicts
Please kindly pull and resolve the conflicts so your PR can be merged as soon as possible

**Comment by TemitopeAgbaje** [comment]
Fixed
please confirm

**Review by babboe1 — CHANGES_REQUESTED** [review]
Hello Again Temitope
for the past 10 minutes, I had to review the changes you made
we have a little problem
You made changes in two files studentdata.json and cloudlord-and-pals/studentdata.json
you are supposed to just add your details to the studentdata.json

Also while trying to fix the merge conflict, some part of people's data was erased 

What you should do to avoid any further error is to create a new branch on your forked repo and pull all changes again
then just add your details again at the bottom of the list

I hope that isn't too much trouble,
Nonetheless, I believe that way will be more efficient and less prone to error 
And it will save us from any further review conflicts

if you do agree with me, Kindly close the pull request and make a new one as soon as you are done 
I will be online to merge it asap

**Comment by TemitopeAgbaje** [comment]
Alright
I would work on it

**Comment by babboe1** [comment]
Hello Temitope,
So many changes has been made since you opened this pull request
 I think its best you add your details again and open a new Pull request 
 Thank you

**Pull request closed without merging**
