### PR TITLE
Pelumi olukayode

### PR DESCRIPTION
**Pull request by OluPel**

### CODE REVIEW

**Comment by OluPel** [comment]
Please kindly merge now made the corrections better in this PR

**Comment by OluPel** [comment]
Thank You

**Review by babboe1 — APPROVED** [review]
Looks Good To me 
There were still some conflicts, but I resolved them from my end
Thank you for contributing 

Don't forget to always check back for issues and if you notice any bugs, please do well to create an issue for it
we will be updating the issues tab as we encounter more changes that need to be made

**Comment by OluPel** [comment]
please can we google meet?

**Comment by babboe1** [comment]
Yes we can Pelumi
https://meet.google.com/erh-teuj-hif
join through the link above

**Pull request merged**
