### PR TITLE
Added Pelumi's profile

### PR DESCRIPTION
**Pull request by OluPel**

### CODE REVIEW

**Comment by OluPel** [comment]
Please Kindly Merge my PR

**Review by babboe1 — CHANGES_REQUESTED** [review]
Hello Pelumi,
Please could you kindly check your code again,
I don't think you pulled the latest change before creating a PR as new data has been added to the file.
someone else had added their profile and has taken the id: 38, down to id: 43
The next one should be id: 44
for more clarity check the image below
image

**Comment by OluPel** [comment]
okay thanks i'd do that now

**Comment by OluPel** [comment]
please kindly check now

**Comment by OluPel** [comment]
I deleted what I added to the previous commit that I did wrongly

**Pull request closed without merging**
